### PR TITLE
Improve support for specialization constants

### PR DESCRIPTION
**Pull request by attackgoat**
This change adds support for inspecting the specialization constant IDs that an array item might have.

Also thank you for this library it is excellent! Feel free to suggest or make edits, I'm not sure what style to go for:
- `nrepeat` was a number but is now an enum, `ArrayBound`; should the field name change to reflect the more expressive API?
- `SpecConstantIntermediate<'_>` embedding itself in `ConstantIntermediate<'_>`; trivial extra memory but maybe not the expected pattern?

### CODE REVIEW

**Comment by PENGUINLIONG** [comment]
Thanks for your contribution! `ArrayBound` looks good to me. But before merging this, I have to spend some more time to work out the best way for it to interacts with specialization constants, and I'd like to share a bit of starter with you.

SPIR-Q might encounter the following cases of array declarations:

1. Multi-binding of descriptors (`nbind` arrays);
2. Case 1 with a specialized number of bindings;
3. Unsized multi-binding of descriptors (with [`GL_EXT_nonuniform_qualifier`](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GL_EXT_nonuniform_qualifier.txt));
4. Statically sized array of data inside a uniform block or storage buffer block;
5. Case 3 with specialized size;
6. Dynamically sized array at the end of a storage buffer block.

AFAIU, you intends to work on case 2 and 5.

First of all, case 5 is not even possible because it conflicts with the specification. Structure members are always decorated with an offset, a fixed literal that cannot be specialized. Specialization of member array sizes change the structure layout - it might not be a problem for an array at the end of the outermost structure, but I cannot think of a reason why not to use unsized array in storage buffers (case 6) for that.

Case 2 can work, but one blocking issue is the `OpSpecConstantOp`. The op is basically a hint to the driver that the operation applied here is a constant-expression with a specialization constant as input; and the result should be also treated as a (specialization) constant too, so that you can write somethings like this:

```glsl
layout(constant_id=123) const int nimg = 1;
layout(binding=0) uniform sampler2D imgs[nimg + 1];
```

which gives:

```spirv
         7(nimg):      6(int) SpecConstant 1
               8:             TypeFloat 32
               9:             TypeImage 8(float) 2D sampled format:Unknown
              10:             TypeSampledImage 9
              11:      6(int) Constant 1
              12:      6(int) SpecConstantOp 128 7(nimg) 11
              13:             TypeArray 10 12
              14:             TypePointer UniformConstant 13
        15(imgs):     14(ptr) Variable UniformConstant
```

And this is basically why I didn't support arrays with specialized sizes before. I'm not sure if it supplies useful information for the user application, if the change in specialization constant value doesn't map linearly with the array size. And even if the user application has enough intelligence to do that, reflecting `SpecId`s might not be necessary too.

Also notice that case 3 (`GL_EXT_nonuniform_qualifier` and its Vulkan counterpart `VK_EXT_descriptor_indexing`) allows multi-bound descriptors to be declared unsized, so supporting *that* feels like a better way out.

**Comment by attackgoat** [comment]
The `OpSpecConstantOp` issue definitely requires further thought.

Could this be handled with another `enum` variant like `ArrayBounds::Specialized(u32, SomeTreeWalker<'a>)`?. The lifetime would be a hassle but workable.

My use case for this feature is both speeding up pipeline creation and also reducing boilerplate for `screen-13` users. It allows me to keep the slow portion of pipeline creation (which take >1ms) outside of the rendering loop. A user provides `screen-13` raw shader code to do this, but the single case of specialized array bounds are tripping me up - as it seem others too!

So _my_ issue could be resolved internally with design changes, but it would be super neat having some ability to query for this.

**Comment by PENGUINLIONG** [comment]
I see, will check it out a bit later. If it sounds good to you I'd add some commits on top of yours.

**Comment by PENGUINLIONG** [comment]
So to my understanding, you need the specialization constant support basically because you want to infer the size of buffers by mere shader reflection, and dynamic arrays lack such information, right?

**Comment by attackgoat** [comment]
> ... you need the specialization constant support basically because you want to infer the size of buffers by mere shader reflection, and dynamic arrays lack such information, right?

Yes - I'm working on an example [here](https://github.com/attackgoat/screen-13/blob/c2d6985d978ab9e9c6dd3a627c14c791ba2c6c95/examples/multipass.rs#L309) that shows how I'm using `spirq-rs` with the proposed change. It removes [this boilerplate](https://github.com/attackgoat/screen-13/commit/3537b0f1ae006273faedaf733dd653857ddb258c#r71459284).

> ... I'd add some commits on top of yours.

That would be awesome!

**Comment by PENGUINLIONG** [comment]
So I looked a bit into this issue and from my standing point I'm reluctant to break the existing APIs. So I suggest a better solution that, I somehow expose an interface to the user application so that the assumed values of spec consts can be fed into the reflection process. And during reflection the spec consts are treated as normal constants; then the array sized can be derived using (probably) your existing codes. It will be a two-step workflow like this:

1. A first-time reflection for the application to learn about what can be specialized in the module.
2. The application feeds SPIR-Q with specialization values regarding to `SpecId`s if it wants to. The spec consts assigned with user input (and the `OpSpecConstantOp`s depending on them) are no longer treated as spec consts but usual literal constants.

If it sounds good to you too I'm gonna continue implementing it.

**Comment by PENGUINLIONG** [comment]
K, I've added `ReflectConfig::specialize(SpecId, ConstantValue)` and constants provided here will replace the default values during reflection. The constants specialized with it will not be listed in `EntryPoint::vars` again. Hope it works in your case :)

**Comment by attackgoat** [comment]
This fits my usage except for the actual type of the constant. My input is a raw [`VkSpecializationInfo`](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSpecializationInfo.html) and so I have the offset, length, and data buffer but I do not have the `u32` vs `f32` detail.

It seems the new code uses that only when asserting and transmuting the value into the needed size.

To generalize this feature, could this API have users provide the raw 4 or 8 bytes instead?
- Removes the `Result` from the `ConstantValue::to_s32` functions
- Removes the indirection from `populate_one_spec_const_op` -> I can demand a value of the desired type be returned

This also would allow for one spec const to be used in multiple numerical contexts; which I assume may be UB.

**Comment by attackgoat** [comment]
Side note: I made the above changes but I accidentally ran `cargo fmt` along the way and so they're wildly unmergeable now. I can redo those changes and put them on a branch if that helps.

**Comment by PENGUINLIONG** [comment]
I get your point and it sounds practical to me. Could you separate the changes from cargo fmt or could you tell me in which branch you applied these changes? I can put them together.

**Comment by PENGUINLIONG** [comment]
I turned to byte buffer for constant values. It eliminates the use of `transmute` and should work with your case.

**Comment by attackgoat** [comment]
Looks awesome - This works great for `screen-13`. Thank for the help!

**Comment by PENGUINLIONG** [comment]
Glad to hear that! I'm merging this then.

**Comment by PENGUINLIONG** [comment]
Now SPIR-Q v0.5.1 has been published with this feature.

**Pull request merged**
